spring:
  application:
    name: bank-notification

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:dummy@gmail.com}
    password: ${MAIL_PASSWORD:dummy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

scheduler:
  enabled: false
  cron:
    daily: "0 0 10 * * ?"
    test: "0 */1 * * * ?"

logging:
  level:
    com.example: INFO
    org.springframework.mail: WARN