spring:
  application:
    name: bank-notification

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:dummy@gmail.com}
    password: ${MAIL_PASSWORD:dummy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_notification
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

repository:
  type: ${REPOSITORY_TYPE:jpa}

scheduler:
  enabled: false
  cron:
    daily: "0 0 10 * * ?"
    test: "0 */1 * * * ?"

logging:
  level:
    com.example: INFO
    org.hibernate.SQL: OFF
    org.springframework.mail: WARN